export const metadata = {
  title: "KalpTree Enterprise Solution",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return <>{children}</>;
}


