

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../store/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import { AdminThemeProvider } from "@/components/admin/ThemeProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KalpTree Enterprise Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add GrapesJS styles */}
        <link
          rel="stylesheet"
          href="https://unpkg.com/grapesjs/dist/css/grapes.min.css"
        />
      </head>
      {/* <body className={`${inter.variable} antialiased`}>

        <ReduxProvider>{children}</ReduxProvider>
        <Toaster />

      </body> */}

       <body className={`${inter.variable} antialiased`}>
        <AdminThemeProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </AdminThemeProvider>
      </body>
    </html>
  );
}
