export const ACCORDION_STYLE_GLASS = {
  layout: {
    layoutStyle: "Flex",
    layoutDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    layoutWrapping: "nowrap",
    alignContent: "flex-start",
    horizontalGap: { value: "0", unit: "px" },
    verticalGap: { value: "12", unit: "px" },
    showInnerShadow: false,
    columnWidths: "Equal Width Columns",
    numberOfColumns: "1",
    collapseEmptyColumns: false,
    gridAutoColumns: "auto",
    rowHeights: "Auto Height Rows",
    numberOfRows: "auto",
    gridAutoRows: "auto",
    gridDirection: "row",
    gridDensity: "normal",
    gridJustifyContent: "start",
    gridAlignItems: "start",
    gridAlignContent: "start",
    gridJustifyItems: "start",
    gridOffsetRules: [],
  },
  sizing: {
    width: { value: "100", unit: "%" },
    maxWidth: { value: "720", unit: "px" },
    sectionAlignment: "center",
    minHeight: { value: "", unit: "auto" },
    height: { value: "", unit: "auto" },
    maxHeight: { value: "", unit: "none" },
  },
  spacing: {
    marginTop: { value: "0", unit: "px" },
    marginBottom: { value: "0", unit: "px" },
    marginLeft: { value: "", unit: "px" },
    marginRight: { value: "", unit: "px" },
    paddingTop: { value: "32", unit: "px" },
    paddingBottom: { value: "32", unit: "px" },
    paddingLeft: { value: "32", unit: "px" },
    paddingRight: { value: "32", unit: "px" },
  },
  border: {
    radiusTopLeft: { value: "20", unit: "px" },
    radiusTopRight: { value: "20", unit: "px" },
    radiusBottomLeft: { value: "20", unit: "px" },
    radiusBottomRight: { value: "20", unit: "px" },
    activeSide: "all",
    allWidth: { value: "1", unit: "px" },
    allColor: "rgba(255,255,255,0.18)",
    allStyle: "Solid",
    topWidth: { value: "1", unit: "px" },
    topColor: "rgba(255,255,255,0.25)",
    topStyle: "Solid",
    rightWidth: { value: "1", unit: "px" },
    rightColor: "rgba(255,255,255,0.18)",
    rightStyle: "Solid",
    bottomWidth: { value: "1", unit: "px" },
    bottomColor: "rgba(255,255,255,0.1)",
    bottomStyle: "Solid",
    leftWidth: { value: "1", unit: "px" },
    leftColor: "rgba(255,255,255,0.18)",
    leftStyle: "Solid",
  },
  boxShadow: {
    presetIndex: 6,
    horizontal: { value: "0", unit: "px" },
    vertical: { value: "0", unit: "px" },
    blur: { value: "40", unit: "px" },
    spread: { value: "0", unit: "px" },
    color: "#6366f1",
    colorOpacity: "25",
    position: "Outer Shadow",
  },
  background: {
    activeTab: "color",
    color: "rgba(255,255,255,0.08)",
    colorOpacity: "100",
    gradientStops: [
      { id: "s1", position: 0, color: "#6366f1", opacity: 100 },
      { id: "s2", position: 100, color: "#8b5cf6", opacity: 100 },
    ],
    gradientType: "Linear",
    gradientPosition: "Center",
    repeatGradient: false,
    gradientLength: "100",
    placeGradientAboveBgImage: false,
    imageUrl: "",
    useParallax: false,
    imageSize: "Cover",
    imagePosition: "Center",
    imageRepeat: "No Repeat",
    imageBlend: "Normal",
    videoMp4: "",
    videoWebm: "",
    videoWidth: "",
    videoHeight: "",
    pauseWhenAnotherPlays: false,
    pauseWhenNotInView: true,
    patternType: "Pills",
    patternColor: "#000000",
    patternColorOpacity: "20",
    patternTransform: "none",
    patternSize: "Actual Size",
    patternRepeatOrigin: "Top Left",
    patternHorizontalOffset: "0",
    patternVerticalOffset: "0",
    patternRepeat: "Repeat",
    patternBlend: "Normal",
    maskType: "Diagonal Bars 2",
    maskColor: "#FFFFFF",
    maskColorOpacity: "100",
    maskTransform: "none",
    maskAspectRatio: "wide",
    maskSize: "Stretch to Fill",
    maskBlend: "Normal",
  },
};

// AccordionItem defaultProps for GLASS style
export const ACCORDION_ITEM_STYLE_GLASS = {
  titletext: {
    activeTag: "H3",
    h1: {
      font: "Default",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#ffffff",
      fontSize: { value: "30", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h2: {
      font: "Default",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#ffffff",
      fontSize: { value: "24", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h3: {
      font: "Default",
      fontWeight: "Semi Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#ffffff",
      fontSize: { value: "17", unit: "px" },
      letterSpacing: { value: "0.2", unit: "px" },
      lineHeight: { value: "1.4", unit: "em" },
      textShadow: 0,
    },
    h4: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#ffffff",
      fontSize: { value: "18", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h5: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#ffffff",
      fontSize: { value: "16", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h6: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#ffffff",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    p: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#ffffff",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
  },
  closedtitletext: {
    activeTag: "H3",
    h3: {
      font: "Default",
      fontWeight: "Semi Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.75)",
      fontSize: { value: "17", unit: "px" },
      letterSpacing: { value: "0.2", unit: "px" },
      lineHeight: { value: "1.4", unit: "em" },
      textShadow: 0,
    },
    h1: {
      font: "Default",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.75)",
      fontSize: { value: "30", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h2: {
      font: "Default",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.75)",
      fontSize: { value: "24", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h4: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.75)",
      fontSize: { value: "18", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h5: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.75)",
      fontSize: { value: "16", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h6: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.75)",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    p: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.75)",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
  },
  bodytext: {
    activeTag: "P",
    p: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.65)",
      fontSize: { value: "15", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.7", unit: "em" },
      textShadow: 0,
    },
    h1: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.65)",
      fontSize: { value: "30", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h2: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.65)",
      fontSize: { value: "24", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h3: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.65)",
      fontSize: { value: "20", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h4: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.65)",
      fontSize: { value: "18", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h5: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.65)",
      fontSize: { value: "16", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h6: {
      font: "Default",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "rgba(255,255,255,0.65)",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
  },
  sizing: {
    width: { value: "100", unit: "%" },
    maxWidth: { value: "", unit: "none" },
    sectionAlignment: "center",
    minHeight: { value: "", unit: "auto" },
    height: { value: "", unit: "auto" },
    maxHeight: { value: "", unit: "none" },
  },
  spacing: {
    marginTop: { value: "0", unit: "px" },
    marginBottom: { value: "0", unit: "px" },
    marginLeft: { value: "", unit: "px" },
    marginRight: { value: "", unit: "px" },
    paddingTop: { value: "4", unit: "px" },
    paddingBottom: { value: "4", unit: "px" },
    paddingLeft: { value: "16", unit: "px" },
    paddingRight: { value: "16", unit: "px" },
  },
  border: {
    radiusTopLeft: { value: "12", unit: "px" },
    radiusTopRight: { value: "12", unit: "px" },
    radiusBottomLeft: { value: "12", unit: "px" },
    radiusBottomRight: { value: "12", unit: "px" },
    activeSide: "all",
    allWidth: { value: "1", unit: "px" },
    allColor: "rgba(255,255,255,0.12)",
    allStyle: "Solid",
    topWidth: { value: "1", unit: "px" },
    topColor: "rgba(255,255,255,0.12)",
    topStyle: "Solid",
    rightWidth: { value: "1", unit: "px" },
    rightColor: "rgba(255,255,255,0.12)",
    rightStyle: "Solid",
    bottomWidth: { value: "1", unit: "px" },
    bottomColor: "rgba(255,255,255,0.12)",
    bottomStyle: "Solid",
    leftWidth: { value: "1", unit: "px" },
    leftColor: "rgba(255,255,255,0.12)",
    leftStyle: "Solid",
  },
  boxShadow: {
    presetIndex: 2,
    horizontal: { value: "0", unit: "px" },
    vertical: { value: "4", unit: "px" },
    blur: { value: "16", unit: "px" },
    spread: { value: "0", unit: "px" },
    color: "#000000",
    colorOpacity: "20",
    position: "Outer Shadow",
  },
  background: {
    activeTab: "color",
    color: "rgba(255,255,255,0.06)",
    colorOpacity: "100",
    gradientStops: [
      { id: "s1", position: 0, color: "#1abc9c", opacity: 100 },
      { id: "s2", position: 100, color: "#3b82f6", opacity: 100 },
    ],
    gradientType: "Linear",
    gradientPosition: "Center",
    repeatGradient: false,
    gradientLength: "100",
    placeGradientAboveBgImage: false,
    imageUrl: "",
    useParallax: false,
    imageSize: "Cover",
    imagePosition: "Center",
    imageRepeat: "No Repeat",
    imageBlend: "Normal",
    videoMp4: "",
    videoWebm: "",
    videoWidth: "",
    videoHeight: "",
    pauseWhenAnotherPlays: false,
    pauseWhenNotInView: true,
    patternType: "Pills",
    patternColor: "#000000",
    patternColorOpacity: "20",
    patternTransform: "none",
    patternSize: "Actual Size",
    patternRepeatOrigin: "Top Left",
    patternHorizontalOffset: "0",
    patternVerticalOffset: "0",
    patternRepeat: "Repeat",
    patternBlend: "Normal",
    maskType: "Diagonal Bars 2",
    maskColor: "#FFFFFF",
    maskColorOpacity: "100",
    maskTransform: "none",
    maskAspectRatio: "wide",
    maskSize: "Stretch to Fill",
    maskBlend: "Normal",
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// STYLE 2: BOLD EDITORIAL
// Stark black borders, high-contrast, newspaper-inspired typography.
// No-nonsense, strong visual hierarchy. Perfect for docs, knowledge bases, FAQs.
// ─────────────────────────────────────────────────────────────────────────────

export const ACCORDION_STYLE_EDITORIAL = {
  layout: {
    layoutStyle: "Flex",
    layoutDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    layoutWrapping: "nowrap",
    alignContent: "flex-start",
    horizontalGap: { value: "0", unit: "px" },
    verticalGap: { value: "0", unit: "px" },
    showInnerShadow: false,
    columnWidths: "Equal Width Columns",
    numberOfColumns: "1",
    collapseEmptyColumns: false,
    gridAutoColumns: "auto",
    rowHeights: "Auto Height Rows",
    numberOfRows: "auto",
    gridAutoRows: "auto",
    gridDirection: "row",
    gridDensity: "normal",
    gridJustifyContent: "start",
    gridAlignItems: "start",
    gridAlignContent: "start",
    gridJustifyItems: "start",
    gridOffsetRules: [],
  },
  sizing: {
    width: { value: "100", unit: "%" },
    maxWidth: { value: "760", unit: "px" },
    sectionAlignment: "center",
    minHeight: { value: "", unit: "auto" },
    height: { value: "", unit: "auto" },
    maxHeight: { value: "", unit: "none" },
  },
  spacing: {
    marginTop: { value: "0", unit: "px" },
    marginBottom: { value: "0", unit: "px" },
    marginLeft: { value: "", unit: "px" },
    marginRight: { value: "", unit: "px" },
    paddingTop: { value: "0", unit: "px" },
    paddingBottom: { value: "0", unit: "px" },
    paddingLeft: { value: "0", unit: "px" },
    paddingRight: { value: "0", unit: "px" },
  },
  border: {
    radiusTopLeft: { value: "0", unit: "px" },
    radiusTopRight: { value: "0", unit: "px" },
    radiusBottomLeft: { value: "0", unit: "px" },
    radiusBottomRight: { value: "0", unit: "px" },
    activeSide: "all",
    allWidth: { value: "2", unit: "px" },
    allColor: "#111111",
    allStyle: "Solid",
    topWidth: { value: "2", unit: "px" },
    topColor: "#111111",
    topStyle: "Solid",
    rightWidth: { value: "2", unit: "px" },
    rightColor: "#111111",
    rightStyle: "Solid",
    bottomWidth: { value: "2", unit: "px" },
    bottomColor: "#111111",
    bottomStyle: "Solid",
    leftWidth: { value: "2", unit: "px" },
    leftColor: "#111111",
    leftStyle: "Solid",
  },
  boxShadow: {
    presetIndex: 7,
    horizontal: { value: "4", unit: "px" },
    vertical: { value: "4", unit: "px" },
    blur: { value: "0", unit: "px" },
    spread: { value: "0", unit: "px" },
    color: "#111111",
    colorOpacity: "100",
    position: "Outer Shadow",
  },
  background: {
    activeTab: "color",
    color: "#ffffff",
    colorOpacity: "100",
    gradientStops: [
      { id: "s1", position: 0, color: "#1abc9c", opacity: 100 },
      { id: "s2", position: 100, color: "#3b82f6", opacity: 100 },
    ],
    gradientType: "Linear",
    gradientPosition: "Center",
    repeatGradient: false,
    gradientLength: "100",
    placeGradientAboveBgImage: false,
    imageUrl: "",
    useParallax: false,
    imageSize: "Cover",
    imagePosition: "Center",
    imageRepeat: "No Repeat",
    imageBlend: "Normal",
    videoMp4: "",
    videoWebm: "",
    videoWidth: "",
    videoHeight: "",
    pauseWhenAnotherPlays: false,
    pauseWhenNotInView: true,
    patternType: "Pills",
    patternColor: "#000000",
    patternColorOpacity: "20",
    patternTransform: "none",
    patternSize: "Actual Size",
    patternRepeatOrigin: "Top Left",
    patternHorizontalOffset: "0",
    patternVerticalOffset: "0",
    patternRepeat: "Repeat",
    patternBlend: "Normal",
    maskType: "Diagonal Bars 2",
    maskColor: "#FFFFFF",
    maskColorOpacity: "100",
    maskTransform: "none",
    maskAspectRatio: "wide",
    maskSize: "Stretch to Fill",
    maskBlend: "Normal",
  },
};

// AccordionItem defaultProps for EDITORIAL style
export const ACCORDION_ITEM_STYLE_EDITORIAL = {
  titletext: {
    activeTag: "H3",
    h1: {
      font: "Georgia",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#111111",
      fontSize: { value: "30", unit: "px" },
      letterSpacing: { value: "-0.5", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h2: {
      font: "Georgia",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#111111",
      fontSize: { value: "24", unit: "px" },
      letterSpacing: { value: "-0.5", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h3: {
      font: "Georgia",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#111111",
      fontSize: { value: "18", unit: "px" },
      letterSpacing: { value: "-0.3", unit: "px" },
      lineHeight: { value: "1.3", unit: "em" },
      textShadow: 0,
    },
    h4: {
      font: "Georgia",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#111111",
      fontSize: { value: "16", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h5: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#111111",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h6: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#111111",
      fontSize: { value: "12", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    p: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#111111",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
  },
  closedtitletext: {
    activeTag: "H3",
    h1: {
      font: "Georgia",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#555555",
      fontSize: { value: "30", unit: "px" },
      letterSpacing: { value: "-0.5", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h2: {
      font: "Georgia",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#555555",
      fontSize: { value: "24", unit: "px" },
      letterSpacing: { value: "-0.5", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h3: {
      font: "Georgia",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#555555",
      fontSize: { value: "18", unit: "px" },
      letterSpacing: { value: "-0.3", unit: "px" },
      lineHeight: { value: "1.3", unit: "em" },
      textShadow: 0,
    },
    h4: {
      font: "Georgia",
      fontWeight: "Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#555555",
      fontSize: { value: "16", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h5: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#555555",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h6: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#555555",
      fontSize: { value: "12", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    p: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#555555",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
  },
  bodytext: {
    activeTag: "P",
    p: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#333333",
      fontSize: { value: "15", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.8", unit: "em" },
      textShadow: 0,
    },
    h1: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#333333",
      fontSize: { value: "30", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h2: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#333333",
      fontSize: { value: "24", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h3: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#333333",
      fontSize: { value: "20", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h4: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#333333",
      fontSize: { value: "18", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h5: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#333333",
      fontSize: { value: "16", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h6: {
      font: "Georgia",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#333333",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
  },
  sizing: {
    width: { value: "100", unit: "%" },
    maxWidth: { value: "", unit: "none" },
    sectionAlignment: "center",
    minHeight: { value: "", unit: "auto" },
    height: { value: "", unit: "auto" },
    maxHeight: { value: "", unit: "none" },
  },
  spacing: {
    marginTop: { value: "0", unit: "px" },
    marginBottom: { value: "-2", unit: "px" },
    marginLeft: { value: "", unit: "px" },
    marginRight: { value: "", unit: "px" },
    paddingTop: { value: "18", unit: "px" },
    paddingBottom: { value: "18", unit: "px" },
    paddingLeft: { value: "20", unit: "px" },
    paddingRight: { value: "20", unit: "px" },
  },
  border: {
    radiusTopLeft: { value: "0", unit: "px" },
    radiusTopRight: { value: "0", unit: "px" },
    radiusBottomLeft: { value: "0", unit: "px" },
    radiusBottomRight: { value: "0", unit: "px" },
    activeSide: "all",
    allWidth: { value: "2", unit: "px" },
    allColor: "#111111",
    allStyle: "Solid",
    topWidth: { value: "2", unit: "px" },
    topColor: "#111111",
    topStyle: "Solid",
    rightWidth: { value: "0", unit: "px" },
    rightColor: "#111111",
    rightStyle: "Solid",
    bottomWidth: { value: "2", unit: "px" },
    bottomColor: "#111111",
    bottomStyle: "Solid",
    leftWidth: { value: "4", unit: "px" },
    leftColor: "#111111",
    leftStyle: "Solid",
  },
  boxShadow: {
    presetIndex: 0,
    horizontal: { value: "0", unit: "px" },
    vertical: { value: "0", unit: "px" },
    blur: { value: "0", unit: "px" },
    spread: { value: "0", unit: "px" },
    color: "#000000",
    colorOpacity: "0",
    position: "Outer Shadow",
  },
  background: {
    activeTab: "color",
    color: "#ffffff",
    colorOpacity: "100",
    gradientStops: [
      { id: "s1", position: 0, color: "#1abc9c", opacity: 100 },
      { id: "s2", position: 100, color: "#3b82f6", opacity: 100 },
    ],
    gradientType: "Linear",
    gradientPosition: "Center",
    repeatGradient: false,
    gradientLength: "100",
    placeGradientAboveBgImage: false,
    imageUrl: "",
    useParallax: false,
    imageSize: "Cover",
    imagePosition: "Center",
    imageRepeat: "No Repeat",
    imageBlend: "Normal",
    videoMp4: "",
    videoWebm: "",
    videoWidth: "",
    videoHeight: "",
    pauseWhenAnotherPlays: false,
    pauseWhenNotInView: true,
    patternType: "Pills",
    patternColor: "#000000",
    patternColorOpacity: "20",
    patternTransform: "none",
    patternSize: "Actual Size",
    patternRepeatOrigin: "Top Left",
    patternHorizontalOffset: "0",
    patternVerticalOffset: "0",
    patternRepeat: "Repeat",
    patternBlend: "Normal",
    maskType: "Diagonal Bars 2",
    maskColor: "#FFFFFF",
    maskColorOpacity: "100",
    maskTransform: "none",
    maskAspectRatio: "wide",
    maskSize: "Stretch to Fill",
    maskBlend: "Normal",
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// STYLE 3: SOFT MINIMAL
// Rounded cards, warm off-white tones, gentle teal-green accents.
// Approachable, clean, spa/wellness/product aesthetic.
// ─────────────────────────────────────────────────────────────────────────────

export const ACCORDION_STYLE_SOFT = {
  layout: {
    layoutStyle: "Flex",
    layoutDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    layoutWrapping: "nowrap",
    alignContent: "flex-start",
    horizontalGap: { value: "0", unit: "px" },
    verticalGap: { value: "10", unit: "px" },
    showInnerShadow: false,
    columnWidths: "Equal Width Columns",
    numberOfColumns: "1",
    collapseEmptyColumns: false,
    gridAutoColumns: "auto",
    rowHeights: "Auto Height Rows",
    numberOfRows: "auto",
    gridAutoRows: "auto",
    gridDirection: "row",
    gridDensity: "normal",
    gridJustifyContent: "start",
    gridAlignItems: "start",
    gridAlignContent: "start",
    gridJustifyItems: "start",
    gridOffsetRules: [],
  },
  sizing: {
    width: { value: "100", unit: "%" },
    maxWidth: { value: "680", unit: "px" },
    sectionAlignment: "center",
    minHeight: { value: "", unit: "auto" },
    height: { value: "", unit: "auto" },
    maxHeight: { value: "", unit: "none" },
  },
  spacing: {
    marginTop: { value: "0", unit: "px" },
    marginBottom: { value: "0", unit: "px" },
    marginLeft: { value: "", unit: "px" },
    marginRight: { value: "", unit: "px" },
    paddingTop: { value: "8", unit: "px" },
    paddingBottom: { value: "8", unit: "px" },
    paddingLeft: { value: "8", unit: "px" },
    paddingRight: { value: "8", unit: "px" },
  },
  border: {
    radiusTopLeft: { value: "24", unit: "px" },
    radiusTopRight: { value: "24", unit: "px" },
    radiusBottomLeft: { value: "24", unit: "px" },
    radiusBottomRight: { value: "24", unit: "px" },
    activeSide: "all",
    allWidth: { value: "0", unit: "px" },
    allColor: "",
    allStyle: "None",
    topWidth: { value: "0", unit: "px" },
    topColor: "",
    topStyle: "None",
    rightWidth: { value: "0", unit: "px" },
    rightColor: "",
    rightStyle: "None",
    bottomWidth: { value: "0", unit: "px" },
    bottomColor: "",
    bottomStyle: "None",
    leftWidth: { value: "0", unit: "px" },
    leftColor: "",
    leftStyle: "None",
  },
  boxShadow: {
    presetIndex: 2,
    horizontal: { value: "0", unit: "px" },
    vertical: { value: "4", unit: "px" },
    blur: { value: "24", unit: "px" },
    spread: { value: "0", unit: "px" },
    color: "#2d6a5e",
    colorOpacity: "8",
    position: "Outer Shadow",
  },
  background: {
    activeTab: "color",
    color: "#fdfaf7",
    colorOpacity: "100",
    gradientStops: [
      { id: "s1", position: 0, color: "#1abc9c", opacity: 100 },
      { id: "s2", position: 100, color: "#3b82f6", opacity: 100 },
    ],
    gradientType: "Linear",
    gradientPosition: "Center",
    repeatGradient: false,
    gradientLength: "100",
    placeGradientAboveBgImage: false,
    imageUrl: "",
    useParallax: false,
    imageSize: "Cover",
    imagePosition: "Center",
    imageRepeat: "No Repeat",
    imageBlend: "Normal",
    videoMp4: "",
    videoWebm: "",
    videoWidth: "",
    videoHeight: "",
    pauseWhenAnotherPlays: false,
    pauseWhenNotInView: true,
    patternType: "Pills",
    patternColor: "#000000",
    patternColorOpacity: "20",
    patternTransform: "none",
    patternSize: "Actual Size",
    patternRepeatOrigin: "Top Left",
    patternHorizontalOffset: "0",
    patternVerticalOffset: "0",
    patternRepeat: "Repeat",
    patternBlend: "Normal",
    maskType: "Diagonal Bars 2",
    maskColor: "#FFFFFF",
    maskColorOpacity: "100",
    maskTransform: "none",
    maskAspectRatio: "wide",
    maskSize: "Stretch to Fill",
    maskBlend: "Normal",
  },
};

// AccordionItem defaultProps for SOFT style
export const ACCORDION_ITEM_STYLE_SOFT = {
  titletext: {
    activeTag: "H3",
    h1: {
      font: "Lato",
      fontWeight: "Semi Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#1a2e29",
      fontSize: { value: "30", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h2: {
      font: "Lato",
      fontWeight: "Semi Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#1a2e29",
      fontSize: { value: "24", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h3: {
      font: "Lato",
      fontWeight: "Semi Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#1a2e29",
      fontSize: { value: "16", unit: "px" },
      letterSpacing: { value: "0.1", unit: "px" },
      lineHeight: { value: "1.4", unit: "em" },
      textShadow: 0,
    },
    h4: {
      font: "Lato",
      fontWeight: "Semi Bold",
      fontStyle: "normal",
      textAlign: "left",
      color: "#1a2e29",
      fontSize: { value: "15", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h5: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#1a2e29",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h6: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#1a2e29",
      fontSize: { value: "13", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    p: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#1a2e29",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
  },
  closedtitletext: {
    activeTag: "H3",
    h1: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#6b8c85",
      fontSize: { value: "30", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h2: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#6b8c85",
      fontSize: { value: "24", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.2", unit: "em" },
      textShadow: 0,
    },
    h3: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#6b8c85",
      fontSize: { value: "16", unit: "px" },
      letterSpacing: { value: "0.1", unit: "px" },
      lineHeight: { value: "1.4", unit: "em" },
      textShadow: 0,
    },
    h4: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#6b8c85",
      fontSize: { value: "15", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h5: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#6b8c85",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h6: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#6b8c85",
      fontSize: { value: "13", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    p: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#6b8c85",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
  },
  bodytext: {
    activeTag: "P",
    p: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#4a6560",
      fontSize: { value: "15", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1.75", unit: "em" },
      textShadow: 0,
    },
    h1: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#4a6560",
      fontSize: { value: "30", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h2: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#4a6560",
      fontSize: { value: "24", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h3: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#4a6560",
      fontSize: { value: "20", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h4: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#4a6560",
      fontSize: { value: "18", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h5: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#4a6560",
      fontSize: { value: "16", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
    h6: {
      font: "Lato",
      fontWeight: "Regular",
      fontStyle: "normal",
      textAlign: "left",
      color: "#4a6560",
      fontSize: { value: "14", unit: "px" },
      letterSpacing: { value: "0", unit: "px" },
      lineHeight: { value: "1", unit: "em" },
      textShadow: 0,
    },
  },
  sizing: {
    width: { value: "100", unit: "%" },
    maxWidth: { value: "", unit: "none" },
    sectionAlignment: "center",
    minHeight: { value: "", unit: "auto" },
    height: { value: "", unit: "auto" },
    maxHeight: { value: "", unit: "none" },
  },
  spacing: {
    marginTop: { value: "0", unit: "px" },
    marginBottom: { value: "0", unit: "px" },
    marginLeft: { value: "", unit: "px" },
    marginRight: { value: "", unit: "px" },
    paddingTop: { value: "6", unit: "px" },
    paddingBottom: { value: "6", unit: "px" },
    paddingLeft: { value: "20", unit: "px" },
    paddingRight: { value: "20", unit: "px" },
  },
  border: {
    radiusTopLeft: { value: "16", unit: "px" },
    radiusTopRight: { value: "16", unit: "px" },
    radiusBottomLeft: { value: "16", unit: "px" },
    radiusBottomRight: { value: "16", unit: "px" },
    activeSide: "all",
    allWidth: { value: "0", unit: "px" },
    allColor: "",
    allStyle: "None",
    topWidth: { value: "0", unit: "px" },
    topColor: "",
    topStyle: "None",
    rightWidth: { value: "0", unit: "px" },
    rightColor: "",
    rightStyle: "None",
    bottomWidth: { value: "0", unit: "px" },
    bottomColor: "",
    bottomStyle: "None",
    leftWidth: { value: "3", unit: "px" },
    leftColor: "#3eb89a",
    leftStyle: "Solid",
  },
  boxShadow: {
    presetIndex: 0,
    horizontal: { value: "0", unit: "px" },
    vertical: { value: "0", unit: "px" },
    blur: { value: "0", unit: "px" },
    spread: { value: "0", unit: "px" },
    color: "#000000",
    colorOpacity: "0",
    position: "Outer Shadow",
  },
  background: {
    activeTab: "color",
    color: "#ffffff",
    colorOpacity: "100",
    gradientStops: [
      { id: "s1", position: 0, color: "#1abc9c", opacity: 100 },
      { id: "s2", position: 100, color: "#3b82f6", opacity: 100 },
    ],
    gradientType: "Linear",
    gradientPosition: "Center",
    repeatGradient: false,
    gradientLength: "100",
    placeGradientAboveBgImage: false,
    imageUrl: "",
    useParallax: false,
    imageSize: "Cover",
    imagePosition: "Center",
    imageRepeat: "No Repeat",
    imageBlend: "Normal",
    videoMp4: "",
    videoWebm: "",
    videoWidth: "",
    videoHeight: "",
    pauseWhenAnotherPlays: false,
    pauseWhenNotInView: true,
    patternType: "Pills",
    patternColor: "#000000",
    patternColorOpacity: "20",
    patternTransform: "none",
    patternSize: "Actual Size",
    patternRepeatOrigin: "Top Left",
    patternHorizontalOffset: "0",
    patternVerticalOffset: "0",
    patternRepeat: "Repeat",
    patternBlend: "Normal",
    maskType: "Diagonal Bars 2",
    maskColor: "#FFFFFF",
    maskColorOpacity: "100",
    maskTransform: "none",
    maskAspectRatio: "wide",
    maskSize: "Stretch to Fill",
    maskBlend: "Normal",
  },
};
