export const metadata = {
  title: 'KalpTree Enterprise Solution',
  description: 'Generated by Next.js',
}

export default function BuilderLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>;
}

