"use client";

import { Render } from "@puckeditor/core";
import { useEffect, useState } from "react";
import { newconfig } from "../puckconfig/newconfig";
import matter from "gray-matter";
import { compileMDX } from "../puckbuilder/Editor";
import * as framerMotion from "framer-motion";

const initialData = {
  root: {
    props: {},
  },
  content: [
    {
      type: "Container",
      props: {
        id: "Container-eae59d64-7f2a-4d61-be3b-c7dd287614ce",
        content: [
          {
            type: "TextBlock",
            props: {
              id: "TextBlock-cb6dad4e-a559-4f6e-a4ef-63209964971e",
              text: {
                activeTag: "p",
                p: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "#3b82f6",
                  fontSize: { value: "14", unit: "px" },
                  letterSpacing: { value: "1", unit: "px" },
                  lineHeight: { value: "1.5", unit: "em" },
                  textShadow: 0,
                },
                h1: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "30", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h2: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "24", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h3: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "20", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h4: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "18", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h5: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "16", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h6: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "14", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
              },
            },
          },
          {
            type: "TextBlock",
            props: {
              id: "TextBlock-b2f927ab-34da-4bdf-b0f0-2fbcb10ad36a",
              text: {
                activeTag: "H1",
                h1: {
                  font: "Default",
                  fontWeight: "Bold",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "#ffffff",
                  fontSize: { value: "48", unit: "px" },
                  letterSpacing: { value: "-1", unit: "px" },
                  lineHeight: { value: "1.1", unit: "em" },
                  textShadow: 0,
                },
                h2: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "24", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h3: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "20", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h4: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "18", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h5: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "16", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h6: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "14", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                p: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "14", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
              },
            },
          },
          {
            type: "TextBlock",
            props: {
              id: "TextBlock-f0f5052d-9cb9-4a52-bc37-90a7279daeb9",
              text: {
                activeTag: "p",
                p: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "#9ca3af",
                  fontSize: { value: "16", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1.6", unit: "em" },
                  textShadow: 0,
                },
                h1: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "30", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h2: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "24", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h3: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "20", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h4: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "18", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h5: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "16", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
                h6: {
                  font: "Default",
                  fontWeight: "Regular",
                  fontStyle: "normal",
                  textAlign: "left",
                  color: "",
                  fontSize: { value: "14", unit: "px" },
                  letterSpacing: { value: "0", unit: "px" },
                  lineHeight: { value: "1", unit: "em" },
                  textShadow: 0,
                },
              },
            },
          },
          {
            type: "Container",
            props: {
              id: "Container-45394988-21cc-4f82-a07a-992af65f51e2",
              content: [
                {
                  type: "Card",
                  props: {
                    id: "Card-4eb1817c-6f58-4bd5-82fb-02fd930030f3",
                    title: "No more shortcodes",
                    description:
                      "Divi 5 adopts a Gutenberg-like approach, replacing shortcodes with a faster and more flexible system.",
                    image:
                      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                    padding: 24,
                  },
                },
                {
                  type: "Card",
                  props: {
                    id: "Card-e4ea5afe-dbb6-4f0e-85e6-55c9fdcef59b",
                    title: "Rebuilt from scratch",
                    description:
                      "Divi 5 is built on a new tech stack and rids itself of a decade of technical debt. It's a lean machine!",
                    image:
                      "https://images.unsplash.com/photo-1518770660439-4636190af475?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                    padding: 24,
                  },
                },
                {
                  type: "Card",
                  props: {
                    id: "Card-3a1ee2b2-6d51-4f8e-8ff5-6d05ac4b0e81",
                    title: "A brand new Divi API",
                    description:
                      "Developers can build custom modules and integrations more easily than ever with Divi's robust new API.",
                    image:
                      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                    padding: 24,
                  },
                },
                {
                  type: "Card",
                  props: {
                    id: "Card-936d7076-05dc-4ffa-8ea3-bec24917c8cd",
                    title: "WordPress storage format",
                    description:
                      "Divi saves content in a block-based format, opening up new possibilities for Gutenberg cross-compatibility.",
                    image:
                      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                    padding: 24,
                  },
                },
              ],
              boxShadow: {
                presetIndex: 0,
                horizontal: { value: "0", unit: "px" },
                vertical: { value: "4", unit: "px" },
                blur: { value: "24", unit: "px" },
                spread: { value: "0", unit: "px" },
                color: "#000000",
                colorOpacity: "40",
                position: "Outer Shadow",
              },
              layout: {
                layoutStyle: "Grid",
                horizontalGap: { value: "24", unit: "px" },
                verticalGap: { value: "24", unit: "px" },
                showInnerShadow: false,
                layoutDirection: "row",
                justifyContent: "center",
                alignItems: "stretch",
                layoutWrapping: "wrap",
                alignContent: "flex-start",
                columnWidths: "Equal Width Columns",
                numberOfColumns: "4",
                collapseEmptyColumns: false,
                gridAutoColumns: "auto",
                rowHeights: "Auto Height Rows",
                numberOfRows: "auto",
                gridAutoRows: "auto",
                gridDirection: "row",
                gridDensity: "normal",
                gridJustifyContent: "start",
                gridAlignItems: "start",
                gridAlignContent: "start",
                gridJustifyItems: "start",
                gridOffsetRules: [],
              },
              sizing: {
                width: { value: "100", unit: "%" },
                maxWidth: { value: "1200", unit: "px" },
                sectionAlignment: "center",
                minHeight: { value: "", unit: "auto" },
                height: { value: "", unit: "auto" },
                maxHeight: { value: "", unit: "none" },
              },
              spacing: {
                marginTop: { value: "48", unit: "px" },
                marginBottom: { value: "0", unit: "px" },
                marginLeft: { value: "", unit: "px" },
                marginRight: { value: "", unit: "px" },
                paddingTop: { value: "0", unit: "px" },
                paddingBottom: { value: "0", unit: "px" },
                paddingLeft: { value: "0", unit: "px" },
                paddingRight: { value: "0", unit: "px" },
              },
              border: {
                radiusTopLeft: { value: "12", unit: "px" },
                radiusTopRight: { value: "12", unit: "px" },
                radiusBottomLeft: { value: "12", unit: "px" },
                radiusBottomRight: { value: "12", unit: "px" },
                activeSide: "all",
                allWidth: { value: "0", unit: "px" },
                allColor: "",
                allStyle: "Solid",
                topWidth: { value: "0", unit: "px" },
                topColor: "",
                topStyle: "Solid",
                rightWidth: { value: "0", unit: "px" },
                rightColor: "",
                rightStyle: "Solid",
                bottomWidth: { value: "0", unit: "px" },
                bottomColor: "",
                bottomStyle: "Solid",
                leftWidth: { value: "0", unit: "px" },
                leftColor: "",
                leftStyle: "Solid",
              },
              background: {
                activeTab: "color",
                color: "",
                colorOpacity: "0",
              },
            },
          },
        ],
        boxShadow: {
          presetIndex: 0,
          horizontal: { value: "0", unit: "px" },
          vertical: { value: "0", unit: "px" },
          blur: { value: "0", unit: "px" },
          spread: { value: "0", unit: "px" },
          color: "#000000",
          colorOpacity: "0",
          position: "Outer Shadow",
        },
        layout: {
          layoutStyle: "Flex",
          horizontalGap: { value: "0", unit: "px" },
          verticalGap: { value: "16", unit: "px" },
          showInnerShadow: false,
          layoutDirection: "column",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          layoutWrapping: "nowrap",
          alignContent: "flex-start",
          columnWidths: "Equal Width Columns",
          numberOfColumns: "1",
          collapseEmptyColumns: false,
          gridAutoColumns: "auto",
          rowHeights: "Auto Height Rows",
          numberOfRows: "auto",
          gridAutoRows: "auto",
          gridDirection: "row",
          gridDensity: "normal",
          gridJustifyContent: "start",
          gridAlignItems: "start",
          gridAlignContent: "start",
          gridJustifyItems: "start",
          gridOffsetRules: [],
        },
        sizing: {
          width: { value: "100", unit: "%" },
          maxWidth: { value: "1200", unit: "px" },
          sectionAlignment: "center",
          minHeight: { value: "", unit: "auto" },
          height: { value: "", unit: "auto" },
          maxHeight: { value: "", unit: "none" },
        },
        spacing: {
          marginTop: { value: "0", unit: "px" },
          marginBottom: { value: "0", unit: "px" },
          marginLeft: { value: "", unit: "px" },
          marginRight: { value: "", unit: "px" },
          paddingTop: { value: "80", unit: "px" },
          paddingBottom: { value: "80", unit: "px" },
          paddingLeft: { value: "48", unit: "px" },
          paddingRight: { value: "48", unit: "px" },
        },
        border: {
          radiusTopLeft: { value: "0", unit: "px" },
          radiusTopRight: { value: "0", unit: "px" },
          radiusBottomLeft: { value: "0", unit: "px" },
          radiusBottomRight: { value: "0", unit: "px" },
          activeSide: "all",
          allWidth: { value: "0", unit: "px" },
          allColor: "",
          allStyle: "Solid",
          topWidth: { value: "0", unit: "px" },
          topColor: "",
          topStyle: "Solid",
          rightWidth: { value: "0", unit: "px" },
          rightColor: "",
          rightStyle: "Solid",
          bottomWidth: { value: "0", unit: "px" },
          bottomColor: "",
          bottomStyle: "Solid",
          leftWidth: { value: "0", unit: "px" },
          leftColor: "",
          leftStyle: "Solid",
        },
        background: {
          activeTab: "color",
          color: "#0a0a0a",
          colorOpacity: "100",
          gradientStops: [
            { id: "s1", position: 0, color: "#1abc9c", opacity: 100 },
            { id: "s2", position: 100, color: "#3b82f6", opacity: 100 },
          ],
          gradientType: "Linear",
          gradientPosition: "Center",
          repeatGradient: false,
          gradientLength: "100",
          placeGradientAboveBgImage: false,
          imageUrl: "",
          useParallax: false,
          imageSize: "Cover",
          imagePosition: "Center",
          imageRepeat: "No Repeat",
          imageBlend: "Normal",
          videoMp4: "",
          videoWebm: "",
          patternType: "Pills",
          patternColor: "#000000",
          patternColorOpacity: "20",
          patternTransform: "none",
          patternSize: "Actual Size",
          patternRepeatOrigin: "Top Left",
          patternHorizontalOffset: "0",
          patternVerticalOffset: "0",
          patternRepeat: "Repeat",
          patternBlend: "Normal",
          maskType: "Diagonal Bars 2",
          maskColor: "#FFFFFF",
          maskColorOpacity: "100",
          maskTransform: "none",
          maskAspectRatio: "wide",
          maskSize: "Stretch to Fill",
          maskBlend: "Normal",
        },
      },
    },
  ],
  zones: {
    "GridBlock-9ba4df6b-c86f-4704-a0e1-d4bfdf5686e0:my-grid": [
      {
        type: "AccordionEditorial",
        props: {
          content: [
            {
              type: "AccordionItem",
              props: {
                id: "AccordionItem-editorial-1",
                titletext: {
                  activeTag: "H3",
                  h1: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "30",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.5",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.2",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h2: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "24",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.5",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.2",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h3: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "18",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.3",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.3",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h4: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "16",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h5: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h6: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "12",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  p: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                },
                closedtitletext: {
                  activeTag: "H3",
                  h1: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "30",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.5",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.2",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h2: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "24",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.5",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.2",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h3: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "18",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.3",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.3",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h4: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "16",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h5: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h6: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "12",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  p: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                },
                bodytext: {
                  activeTag: "P",
                  p: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "15",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.8",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h1: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "30",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h2: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "24",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h3: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "20",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h4: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "18",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h5: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "16",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h6: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                },
                sizing: {
                  width: {
                    value: "100",
                    unit: "%",
                  },
                  maxWidth: {
                    value: "",
                    unit: "none",
                  },
                  sectionAlignment: "center",
                  minHeight: {
                    value: "",
                    unit: "auto",
                  },
                  height: {
                    value: "",
                    unit: "auto",
                  },
                  maxHeight: {
                    value: "",
                    unit: "none",
                  },
                },
                spacing: {
                  marginTop: {
                    value: "0",
                    unit: "px",
                  },
                  marginBottom: {
                    value: "-2",
                    unit: "px",
                  },
                  marginLeft: {
                    value: "",
                    unit: "px",
                  },
                  marginRight: {
                    value: "",
                    unit: "px",
                  },
                  paddingTop: {
                    value: "18",
                    unit: "px",
                  },
                  paddingBottom: {
                    value: "18",
                    unit: "px",
                  },
                  paddingLeft: {
                    value: "20",
                    unit: "px",
                  },
                  paddingRight: {
                    value: "20",
                    unit: "px",
                  },
                },
                border: {
                  radiusTopLeft: {
                    value: "0",
                    unit: "px",
                  },
                  radiusTopRight: {
                    value: "0",
                    unit: "px",
                  },
                  radiusBottomLeft: {
                    value: "0",
                    unit: "px",
                  },
                  radiusBottomRight: {
                    value: "0",
                    unit: "px",
                  },
                  activeSide: "all",
                  allWidth: {
                    value: "2",
                    unit: "px",
                  },
                  allColor: "#111111",
                  allStyle: "Solid",
                  topWidth: {
                    value: "2",
                    unit: "px",
                  },
                  topColor: "#111111",
                  topStyle: "Solid",
                  rightWidth: {
                    value: "0",
                    unit: "px",
                  },
                  rightColor: "#111111",
                  rightStyle: "Solid",
                  bottomWidth: {
                    value: "2",
                    unit: "px",
                  },
                  bottomColor: "#111111",
                  bottomStyle: "Solid",
                  leftWidth: {
                    value: "4",
                    unit: "px",
                  },
                  leftColor: "#111111",
                  leftStyle: "Solid",
                },
                boxShadow: {
                  presetIndex: 0,
                  horizontal: {
                    value: "0",
                    unit: "px",
                  },
                  vertical: {
                    value: "0",
                    unit: "px",
                  },
                  blur: {
                    value: "0",
                    unit: "px",
                  },
                  spread: {
                    value: "0",
                    unit: "px",
                  },
                  color: "#000000",
                  colorOpacity: "0",
                  position: "Outer Shadow",
                },
                background: {
                  activeTab: "color",
                  color: "#ffffff",
                  colorOpacity: "100",
                  gradientStops: [
                    {
                      id: "s1",
                      position: 0,
                      color: "#1abc9c",
                      opacity: 100,
                    },
                    {
                      id: "s2",
                      position: 100,
                      color: "#3b82f6",
                      opacity: 100,
                    },
                  ],
                  gradientType: "Linear",
                  gradientPosition: "Center",
                  repeatGradient: false,
                  gradientLength: "100",
                  placeGradientAboveBgImage: false,
                  imageUrl: "",
                  useParallax: false,
                  imageSize: "Cover",
                  imagePosition: "Center",
                  imageRepeat: "No Repeat",
                  imageBlend: "Normal",
                  videoMp4: "",
                  videoWebm: "",
                  videoWidth: "",
                  videoHeight: "",
                  pauseWhenAnotherPlays: false,
                  pauseWhenNotInView: true,
                  patternType: "Pills",
                  patternColor: "#000000",
                  patternColorOpacity: "20",
                  patternTransform: "none",
                  patternSize: "Actual Size",
                  patternRepeatOrigin: "Top Left",
                  patternHorizontalOffset: "0",
                  patternVerticalOffset: "0",
                  patternRepeat: "Repeat",
                  patternBlend: "Normal",
                  maskType: "Diagonal Bars 2",
                  maskColor: "#FFFFFF",
                  maskColorOpacity: "100",
                  maskTransform: "none",
                  maskAspectRatio: "wide",
                  maskSize: "Stretch to Fill",
                  maskBlend: "Normal",
                },
              },
            },
          ],
          layout: {
            layoutStyle: "Flex",
            layoutDirection: "column",
            justifyContent: "flex-start",
            alignItems: "stretch",
            layoutWrapping: "nowrap",
            alignContent: "flex-start",
            horizontalGap: {
              value: "0",
              unit: "px",
            },
            verticalGap: {
              value: "0",
              unit: "px",
            },
            showInnerShadow: false,
            columnWidths: "Equal Width Columns",
            numberOfColumns: "1",
            collapseEmptyColumns: false,
            gridAutoColumns: "auto",
            rowHeights: "Auto Height Rows",
            numberOfRows: "auto",
            gridAutoRows: "auto",
            gridDirection: "row",
            gridDensity: "normal",
            gridJustifyContent: "start",
            gridAlignItems: "start",
            gridAlignContent: "start",
            gridJustifyItems: "start",
            gridOffsetRules: [],
          },
          sizing: {
            width: {
              value: "100",
              unit: "%",
            },
            maxWidth: {
              value: "760",
              unit: "px",
            },
            sectionAlignment: "center",
            minHeight: {
              value: "",
              unit: "auto",
            },
            height: {
              value: "",
              unit: "auto",
            },
            maxHeight: {
              value: "",
              unit: "none",
            },
          },
          spacing: {
            marginTop: {
              value: "0",
              unit: "px",
            },
            marginBottom: {
              value: "0",
              unit: "px",
            },
            marginLeft: {
              value: "",
              unit: "px",
            },
            marginRight: {
              value: "",
              unit: "px",
            },
            paddingTop: {
              value: "0",
              unit: "px",
            },
            paddingBottom: {
              value: "0",
              unit: "px",
            },
            paddingLeft: {
              value: "0",
              unit: "px",
            },
            paddingRight: {
              value: "0",
              unit: "px",
            },
          },
          border: {
            radiusTopLeft: {
              value: "0",
              unit: "px",
            },
            radiusTopRight: {
              value: "0",
              unit: "px",
            },
            radiusBottomLeft: {
              value: "0",
              unit: "px",
            },
            radiusBottomRight: {
              value: "0",
              unit: "px",
            },
            activeSide: "all",
            allWidth: {
              value: "2",
              unit: "px",
            },
            allColor: "#111111",
            allStyle: "Solid",
            topWidth: {
              value: "2",
              unit: "px",
            },
            topColor: "#111111",
            topStyle: "Solid",
            rightWidth: {
              value: "2",
              unit: "px",
            },
            rightColor: "#111111",
            rightStyle: "Solid",
            bottomWidth: {
              value: "2",
              unit: "px",
            },
            bottomColor: "#111111",
            bottomStyle: "Solid",
            leftWidth: {
              value: "2",
              unit: "px",
            },
            leftColor: "#111111",
            leftStyle: "Solid",
          },
          boxShadow: {
            presetIndex: 7,
            horizontal: {
              value: "4",
              unit: "px",
            },
            vertical: {
              value: "4",
              unit: "px",
            },
            blur: {
              value: "0",
              unit: "px",
            },
            spread: {
              value: "0",
              unit: "px",
            },
            color: "#111111",
            colorOpacity: "100",
            position: "Outer Shadow",
          },
          background: {
            activeTab: "color",
            color: "#ffffff",
            colorOpacity: "100",
            gradientStops: [
              {
                id: "s1",
                position: 0,
                color: "#1abc9c",
                opacity: 100,
              },
              {
                id: "s2",
                position: 100,
                color: "#3b82f6",
                opacity: 100,
              },
            ],
            gradientType: "Linear",
            gradientPosition: "Center",
            repeatGradient: false,
            gradientLength: "100",
            placeGradientAboveBgImage: false,
            imageUrl: "",
            useParallax: false,
            imageSize: "Cover",
            imagePosition: "Center",
            imageRepeat: "No Repeat",
            imageBlend: "Normal",
            videoMp4: "",
            videoWebm: "",
            videoWidth: "",
            videoHeight: "",
            pauseWhenAnotherPlays: false,
            pauseWhenNotInView: true,
            patternType: "Pills",
            patternColor: "#000000",
            patternColorOpacity: "20",
            patternTransform: "none",
            patternSize: "Actual Size",
            patternRepeatOrigin: "Top Left",
            patternHorizontalOffset: "0",
            patternVerticalOffset: "0",
            patternRepeat: "Repeat",
            patternBlend: "Normal",
            maskType: "Diagonal Bars 2",
            maskColor: "#FFFFFF",
            maskColorOpacity: "100",
            maskTransform: "none",
            maskAspectRatio: "wide",
            maskSize: "Stretch to Fill",
            maskBlend: "Normal",
          },
          id: "AccordionEditorial-98c38efd-7d56-489b-b393-eb313a968263",
        },
      },
      {
        type: "AccordionEditorial",
        props: {
          content: [
            {
              type: "AccordionItem",
              props: {
                id: "AccordionItem-99850bfe-e260-4800-a70a-3d4afde32a9e",
                titletext: {
                  activeTag: "H3",
                  h1: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "30",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.5",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.2",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h2: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "24",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.5",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.2",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h3: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "18",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.3",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.3",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h4: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "16",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h5: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h6: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "12",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  p: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#111111",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                },
                closedtitletext: {
                  activeTag: "H3",
                  h1: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "30",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.5",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.2",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h2: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "24",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.5",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.2",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h3: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "18",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "-0.3",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.3",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h4: {
                    font: "Georgia",
                    fontWeight: "Bold",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "16",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h5: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h6: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "12",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  p: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#555555",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                },
                bodytext: {
                  activeTag: "P",
                  p: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "15",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1.8",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h1: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "30",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h2: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "24",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h3: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "20",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h4: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "18",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h5: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "16",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                  h6: {
                    font: "Georgia",
                    fontWeight: "Regular",
                    fontStyle: "normal",
                    textAlign: "left",
                    color: "#333333",
                    fontSize: {
                      value: "14",
                      unit: "px",
                    },
                    letterSpacing: {
                      value: "0",
                      unit: "px",
                    },
                    lineHeight: {
                      value: "1",
                      unit: "em",
                    },
                    textShadow: 0,
                  },
                },
                sizing: {
                  width: {
                    value: "100",
                    unit: "%",
                  },
                  maxWidth: {
                    value: "",
                    unit: "none",
                  },
                  sectionAlignment: "center",
                  minHeight: {
                    value: "",
                    unit: "auto",
                  },
                  height: {
                    value: "",
                    unit: "auto",
                  },
                  maxHeight: {
                    value: "",
                    unit: "none",
                  },
                },
                spacing: {
                  marginTop: {
                    value: "0",
                    unit: "px",
                  },
                  marginBottom: {
                    value: "-2",
                    unit: "px",
                  },
                  marginLeft: {
                    value: "",
                    unit: "px",
                  },
                  marginRight: {
                    value: "",
                    unit: "px",
                  },
                  paddingTop: {
                    value: "18",
                    unit: "px",
                  },
                  paddingBottom: {
                    value: "18",
                    unit: "px",
                  },
                  paddingLeft: {
                    value: "20",
                    unit: "px",
                  },
                  paddingRight: {
                    value: "20",
                    unit: "px",
                  },
                },
                border: {
                  radiusTopLeft: {
                    value: "0",
                    unit: "px",
                  },
                  radiusTopRight: {
                    value: "0",
                    unit: "px",
                  },
                  radiusBottomLeft: {
                    value: "0",
                    unit: "px",
                  },
                  radiusBottomRight: {
                    value: "0",
                    unit: "px",
                  },
                  activeSide: "all",
                  allWidth: {
                    value: "2",
                    unit: "px",
                  },
                  allColor: "#111111",
                  allStyle: "Solid",
                  topWidth: {
                    value: "2",
                    unit: "px",
                  },
                  topColor: "#111111",
                  topStyle: "Solid",
                  rightWidth: {
                    value: "0",
                    unit: "px",
                  },
                  rightColor: "#111111",
                  rightStyle: "Solid",
                  bottomWidth: {
                    value: "2",
                    unit: "px",
                  },
                  bottomColor: "#111111",
                  bottomStyle: "Solid",
                  leftWidth: {
                    value: "4",
                    unit: "px",
                  },
                  leftColor: "#111111",
                  leftStyle: "Solid",
                },
                boxShadow: {
                  presetIndex: 0,
                  horizontal: {
                    value: "0",
                    unit: "px",
                  },
                  vertical: {
                    value: "0",
                    unit: "px",
                  },
                  blur: {
                    value: "0",
                    unit: "px",
                  },
                  spread: {
                    value: "0",
                    unit: "px",
                  },
                  color: "#000000",
                  colorOpacity: "0",
                  position: "Outer Shadow",
                },
                background: {
                  activeTab: "color",
                  color: "#ffffff",
                  colorOpacity: "100",
                  gradientStops: [
                    {
                      id: "s1",
                      position: 0,
                      color: "#1abc9c",
                      opacity: 100,
                    },
                    {
                      id: "s2",
                      position: 100,
                      color: "#3b82f6",
                      opacity: 100,
                    },
                  ],
                  gradientType: "Linear",
                  gradientPosition: "Center",
                  repeatGradient: false,
                  gradientLength: "100",
                  placeGradientAboveBgImage: false,
                  imageUrl: "",
                  useParallax: false,
                  imageSize: "Cover",
                  imagePosition: "Center",
                  imageRepeat: "No Repeat",
                  imageBlend: "Normal",
                  videoMp4: "",
                  videoWebm: "",
                  videoWidth: "",
                  videoHeight: "",
                  pauseWhenAnotherPlays: false,
                  pauseWhenNotInView: true,
                  patternType: "Pills",
                  patternColor: "#000000",
                  patternColorOpacity: "20",
                  patternTransform: "none",
                  patternSize: "Actual Size",
                  patternRepeatOrigin: "Top Left",
                  patternHorizontalOffset: "0",
                  patternVerticalOffset: "0",
                  patternRepeat: "Repeat",
                  patternBlend: "Normal",
                  maskType: "Diagonal Bars 2",
                  maskColor: "#FFFFFF",
                  maskColorOpacity: "100",
                  maskTransform: "none",
                  maskAspectRatio: "wide",
                  maskSize: "Stretch to Fill",
                  maskBlend: "Normal",
                },
              },
            },
          ],
          layout: {
            layoutStyle: "Flex",
            layoutDirection: "column",
            justifyContent: "flex-start",
            alignItems: "stretch",
            layoutWrapping: "nowrap",
            alignContent: "flex-start",
            horizontalGap: {
              value: "0",
              unit: "px",
            },
            verticalGap: {
              value: "0",
              unit: "px",
            },
            showInnerShadow: false,
            columnWidths: "Equal Width Columns",
            numberOfColumns: "1",
            collapseEmptyColumns: false,
            gridAutoColumns: "auto",
            rowHeights: "Auto Height Rows",
            numberOfRows: "auto",
            gridAutoRows: "auto",
            gridDirection: "row",
            gridDensity: "normal",
            gridJustifyContent: "start",
            gridAlignItems: "start",
            gridAlignContent: "start",
            gridJustifyItems: "start",
            gridOffsetRules: [],
          },
          sizing: {
            width: {
              value: "100",
              unit: "%",
            },
            maxWidth: {
              value: "760",
              unit: "px",
            },
            sectionAlignment: "center",
            minHeight: {
              value: "",
              unit: "auto",
            },
            height: {
              value: "",
              unit: "auto",
            },
            maxHeight: {
              value: "",
              unit: "none",
            },
          },
          spacing: {
            marginTop: {
              value: "0",
              unit: "px",
            },
            marginBottom: {
              value: "0",
              unit: "px",
            },
            marginLeft: {
              value: "",
              unit: "px",
            },
            marginRight: {
              value: "",
              unit: "px",
            },
            paddingTop: {
              value: "0",
              unit: "px",
            },
            paddingBottom: {
              value: "0",
              unit: "px",
            },
            paddingLeft: {
              value: "0",
              unit: "px",
            },
            paddingRight: {
              value: "0",
              unit: "px",
            },
          },
          border: {
            radiusTopLeft: {
              value: "0",
              unit: "px",
            },
            radiusTopRight: {
              value: "0",
              unit: "px",
            },
            radiusBottomLeft: {
              value: "0",
              unit: "px",
            },
            radiusBottomRight: {
              value: "0",
              unit: "px",
            },
            activeSide: "all",
            allWidth: {
              value: "2",
              unit: "px",
            },
            allColor: "#111111",
            allStyle: "Solid",
            topWidth: {
              value: "2",
              unit: "px",
            },
            topColor: "#111111",
            topStyle: "Solid",
            rightWidth: {
              value: "2",
              unit: "px",
            },
            rightColor: "#111111",
            rightStyle: "Solid",
            bottomWidth: {
              value: "2",
              unit: "px",
            },
            bottomColor: "#111111",
            bottomStyle: "Solid",
            leftWidth: {
              value: "2",
              unit: "px",
            },
            leftColor: "#111111",
            leftStyle: "Solid",
          },
          boxShadow: {
            presetIndex: 7,
            horizontal: {
              value: "4",
              unit: "px",
            },
            vertical: {
              value: "4",
              unit: "px",
            },
            blur: {
              value: "0",
              unit: "px",
            },
            spread: {
              value: "0",
              unit: "px",
            },
            color: "#111111",
            colorOpacity: "100",
            position: "Outer Shadow",
          },
          background: {
            activeTab: "color",
            color: "#ffffff",
            colorOpacity: "100",
            gradientStops: [
              {
                id: "s1",
                position: 0,
                color: "#1abc9c",
                opacity: 100,
              },
              {
                id: "s2",
                position: 100,
                color: "#3b82f6",
                opacity: 100,
              },
            ],
            gradientType: "Linear",
            gradientPosition: "Center",
            repeatGradient: false,
            gradientLength: "100",
            placeGradientAboveBgImage: false,
            imageUrl: "",
            useParallax: false,
            imageSize: "Cover",
            imagePosition: "Center",
            imageRepeat: "No Repeat",
            imageBlend: "Normal",
            videoMp4: "",
            videoWebm: "",
            videoWidth: "",
            videoHeight: "",
            pauseWhenAnotherPlays: false,
            pauseWhenNotInView: true,
            patternType: "Pills",
            patternColor: "#000000",
            patternColorOpacity: "20",
            patternTransform: "none",
            patternSize: "Actual Size",
            patternRepeatOrigin: "Top Left",
            patternHorizontalOffset: "0",
            patternVerticalOffset: "0",
            patternRepeat: "Repeat",
            patternBlend: "Normal",
            maskType: "Diagonal Bars 2",
            maskColor: "#FFFFFF",
            maskColorOpacity: "100",
            maskTransform: "none",
            maskAspectRatio: "wide",
            maskSize: "Stretch to Fill",
            maskBlend: "Normal",
          },
          id: "AccordionEditorial-1d5183eb-7218-4da2-b13b-112f6f0c18c7",
        },
      },
    ],
  },
};

export default function RenderPage() {
  const [config, setConfig] = useState<any>(newconfig);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const res = await fetch("/hero.mdx");
        const text = await res.text();
        const { content, data: frontmatter } = matter(text);
        const CompiledHero = await compileMDX(content);

        const HeroBlock = {
          label: "Hero Block (MDX)",
          fields: {
            heading: { type: "text" as const, label: "Heading" },
            subheading: { type: "text" as const, label: "Subheading" },
            primaryButtonLabel: {
              type: "text" as const,
              label: "Primary Button",
            },
            primaryButtonHref: {
              type: "text" as const,
              label: "Primary Button URL",
            },
            secondaryButtonLabel: {
              type: "text" as const,
              label: "Secondary Button",
            },
            background: {
              type: "text" as const,
              label: "Background (CSS gradient or color)",
            },
          },
          defaultProps: {
            heading: frontmatter.heading ?? "Build Faster. Ship Smarter.",
            subheading:
              frontmatter.subheading ??
              "The modern platform for teams who want to move fast.",
            primaryButtonLabel: frontmatter.primaryBtn ?? "Get Started",
            primaryButtonHref: frontmatter.primaryHref ?? "#",
            secondaryButtonLabel: frontmatter.secondaryBtn ?? "Learn More",
            background:
              frontmatter.background ??
              "linear-gradient(135deg, #0f0f0f 0%, #1a1a2e 100%)",
          },
          render: (props: any) => (
            <CompiledHero {...props} motion={framerMotion.motion} />
          ),
        };

        setConfig((prev: any) => ({
          ...prev,
          components: { ...prev.components, HeroBlock },
        }));
      } catch (err) {
        console.error("Failed to load MDX block:", err);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  if (loading) {
    return (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          height: "100vh",
          background: "#0d0d0d",
          color: "#555",
          fontFamily: "monospace",
          fontSize: 13,
          letterSpacing: "0.08em",
        }}
      >
        loading blocks...
      </div>
    );
  }

  return <Render config={config} data={initialData} />;
}
